### ISSUE TITLE
Add licence section to NDE terminology requirements/ datasets?

### ISSUE THREAD

**Issue by rschalkrce** [netwerk-digitaal-erfgoed/network-of-terms#1003]
Currently the [requirements terminologiebronnen](https://netwerk-digitaal-erfgoed.github.io/requirements-terminologiebronnen/) has no section/ recommendation on licenses (which are mentioned in [NDE dataset requirements](https://netwerk-digitaal-erfgoed.github.io/requirements-datasets/#dataset-license)). 

Would be good to discuss license requirements, and add licenses to the [dataset descriptions](https://github.com/netwerk-digitaal-erfgoed/network-of-terms/tree/master/packages/network-of-terms-catalog/catalog/datasets).

**Comment by ddeboer** [comment]
Terminology sources are a subset of datasets. That’s why the _Requirements terminologiebronnen_ state:

> Dit document beschrijft enkel de requirements die specifiek gelden voor bronhouders van terminologiebronnen. Daarnaast zijn er algemene requirements die gelden voor alle bronhouders, ongeacht het soort informatie dat zij aanbieden. Deze requirements worden uitgewerkt in een opzichzelfstaand [document voor datasets](https://netwerk-digitaal-erfgoed.github.io/requirements-terminologiebronnen/#biblio-nde-datasets).

So license belongs to the dataset description proper. @rschalkrce For your information, we’re planning to move (part of) the Network of Terms catalog to the Dataset Register (#795), where the license must indeed be made available. The Network of Terms catalog can then be stripped down to contain only information that we need here, such as the SPARQL queries used to generate results.

**Comment by rschalkrce** [comment]
@ddeboer thanks! Does that mean we can close this issue, or do we still need to reach out to bronhouders of term lists to provide us with license information?

**Comment by ddeboer** [comment]
Yes, let’s close this.
