### ISSUE TITLE
Document language of sources

### ISSUE THREAD

**Issue by nichtich** [netwerk-digitaal-erfgoed/network-of-terms#1105]
Each source is configured with as static language and the label are returned in this language but the language of labels is not included in GraphQL results. Please add a catalog field `language` for each source and configure the language in `catalog/datasets/`, e.g.

~~~json
"language": { "@value": "nl" }
~~~

So query

~~~graphql
query {
  sources {
    uri
    name
    description
    language
  }
}
~~~

results in

~~~json
    {
        "uri": "https://druid.datalegend.net/AdamNet/Geography/sparql#streets",
        "name": "Adamlink: straten in Amsterdam",
        "description": "Straten in Amsterdam",
        "language": "nl"
    }
~~~

**Comment by EnnoMeijers** [comment]
To stay compliant with the internally used Schema.org vocab I suggest to use `availableLanguage` which is a Schema.org properities, `language` is not.

**Comment by ddeboer** [comment]
@EnnoMeijers `schema:inLanguage` seems more appropriate.

**Comment by EnnoMeijers** [comment]
I agree about schema:inLanguage, I had the same idea later. 

As I understood it is about the language used for queries and the returned terms and making this explicit in the dataset description. Based on this parameter a selection of sources can be made that support a specific language (English in this use case).

**Comment by EnnoMeijers** [comment]
As schema:inLanguage is now a required field for the dataset definitions documentation should be updated at least at https://github.com/netwerk-digitaal-erfgoed/network-of-terms/tree/master/packages/network-of-terms-catalog. 

It also is a breaking change for instances running their own catalog version (if any?) do we have a way to communicate this?

**Comment by ddeboer** [comment]
> As schema:inLanguage is now a required field for the dataset definitions documentation should be updated at least at https://github.com/netwerk-digitaal-erfgoed/network-of-terms/tree/master/packages/network-of-terms-catalog.

No, because it says:

> Most of the dataset’s properties match the [NDE Requirements for Datasets](https://netwerk-digitaal-erfgoed.github.io/requirements-datasets)…

And `inLanguage` is defined there.

> It also is a breaking change for instances running their own catalog version (if any?) do we have a way to communicate this?

True, we probably should have annotated this commit to say so, causing a new major version to be published (following semver). However, it’s too late for that now.

**Comment by EnnoMeijers** [comment]
Sorry for nagging but in the Dataset requirements schema:inLanguage is a **recommend** property and not a **required** property as it is now for the NoT, so making this explicit is helpful for the user.

**Comment by ddeboer** [comment]
Ah, good point! Updated the docs in 714cd73.
