### ISSUE TITLE
Lookup on Brabantse Gebouwen URI's gives no results

### ISSUE THREAD

**Issue by rschalkrce** [netwerk-digitaal-erfgoed/network-of-terms#1125]
The Lookup function on the Brabantse Gebouwen dataset URI's currently does not work. 

E.g. `https://n2t.net/ark:/15052/0df1561e-db7b-4be7-ae96-118d8ac5c4a1` returns `No source found that can provide term with URI https://n2t.net/ark:/15052/0df1561e-db7b-4be7-ae96-118d8ac5c4a1` on the GraphQL API. 

They recently moved to new URI's, but the Search does still work on these new URI's.

**Comment by ddeboer** [comment]
> `No source found that can provide term with URI https://n2t.net/ark:/15052/51a4f73f-d9e2-4ecc-a32f-1d8d512a420c"`

This error message seems clear enough? Especially combined with the fact that the source has changed URIs.

As [documented](https://github.com/netwerk-digitaal-erfgoed/network-of-terms/blob/6c6f31d1c63fc74304805c1d0614200a9ae9daff/packages/network-of-terms-catalog/README.md#data-model), the `schema:url` for this source needs to be changed in the catalog.
