### ISSUE TITLE
Wikidata SPARQL endpoint changes per March 2025

### ISSUE THREAD

**Issue by rschalkrce** [netwerk-digitaal-erfgoed/network-of-terms#1432]
The Wikidata endpoint will be split in two endpoints, and the current endpoint NoT uses will be discontinued per March 2025.

We should move to the new endpoint and test our queries beforehand.

Info: https://www.wikidata.org/wiki/Wikidata:SPARQL_query_service/WDQS_backend_update/September_2024_scaling_update

**Comment by ddeboer** [comment]
Thanks for the heads-up @rschalkrce.

As far as I can tell, we don’t have to do anything, as query.wikidata.org will continue to be available after March 2025:

> The “query.wikidata.org” endpoint is still here and will continue to serve the full Wikidata graph for a transition period, with the period ending in March 2025. After the transition, it will only serve the main graph.

The main graph is all we need.
