### ISSUE TITLE
Git commit fails on Windows

### ISSUE THREAD

**Issue by rschalkrce** [netwerk-digitaal-erfgoed/network-of-terms#1445]
Since a couple of weeks `git commit` fails on my Windows machine for this repository. May be related to accepting only Unix-style paths?

When committing I now get this message: ```
/bin/bash: C:/Program Files/nodejs/npx: No such file or directory
husky - commit-msg script failed (code 127)
husky - command not found in PATH= [etc.]```

The PATH variable does exist in my environment. Commits to other repositories from my machine still work fine. I have been unable to solve it myself.

**Comment by ddeboer** [comment]
Did you run `npm install`?

**Comment by rschalkrce** [comment]
Yes, also re-installed npm and husky, but to no avail

**Comment by ddeboer** [comment]
It seems `npx` cannot be found.

Does `C:/Program Files/nodejs/npx` exist and is it executable? What happens if you run `npx` in your terminal?

**Comment by rschalkrce** [comment]
Yes it does exist and is part of `PATH`. Could it have to do with the preceding `/bin/bash` part, since I work from Windows? 

Running `npx --version` in Powershell:
`10.8.2`

Running `npx --version` in Ubuntu:
`10.8.2`

**Comment by ddeboer** [comment]
And `bash -c 'npx --version'`?

**Comment by rschalkrce** [comment]
PS C:\Users\Ruben> bash -c 'npx --version':
6.14.4

**Comment by ddeboer** [comment]
I’m not sure why you’re getting `bash`, because Husky runs `sh`. Are you running the `git commit` in a bash shell?

**Comment by ddeboer** [comment]
Please pull master and try again.
