### ISSUE TITLE
GraphQL: pagination/limit support for Terms

### ISSUE THREAD

**Issue by wivaku** [netwerk-digitaal-erfgoed/network-of-terms#1477]
Would be useful to have pagination support, and/or to limit the results.
 
Certain sources return many terms, e.g. when searching for a city name in source https://www.wikidata.org/#entities-streets

**Comment by ddeboer** [comment]
Hey @wivaku, thanks for your suggestion! 

So I fully understand your use case: do you want to primarily limit large lists of results (limit) or do you also need to process subsequent pages (limit with offset)?

Our assumption thus far has been that reading through more than a couple of dozens results isn’t really useful. In that case the user should probably refine their search query to reduce the results.

**Comment by wivaku** [comment]
Indeed, the primary case is to limit a large set of results.
Pagination (for either main or sub) is indeed a lower priority.

**Comment by ddeboer** [comment]
You can now limit the results in the GraphQL API using a new `limit` parameter:

```graphql
query {
  terms(
    sources: ["https://data.muziekschatten.nl/sparql/#klassiekewerken"],
    query: "sas"
    limit: 5 
  ) {
  ...
```
