### ISSUE TITLE
Authentication for terminology sources

### ISSUE THREAD

**Issue by ddeboer** [netwerk-digitaal-erfgoed/network-of-terms#478]
The new GTAA endpoint will require an authentication key. Currently, the Network of Terms doesn’t support authenticated endpoints.

@wmelder Can you elaborate a bit on what that authentication will look like? A single API key in an HTTP header or something else?

**Comment by wmelder** [comment]
The SPARQL endpoint requires basic authentication. 

``In order to authenticate you need to request a mam account at nisv with at least group THES_API_70_BROWSE.``
> I will manage this for you. You will need to be registered in de LDAP server. The reason is that management wants to know whether services are used or not and by whom.

``You can send the credentials using basic auth or the request parameter 'key'. In the latter case, make sure you connect via https.``
> I tested it with basic auth, not the other method using 'key'. Using basic auth it is just a matter of adding the user and password to the HTTP request. Using [python requests](https://docs.python-requests.org/en/master/user/authentication/) this was as easy as adding auth=(user, passw) to the get request. 

Maybe needless to say, but the credentials are to be kept secret. Using HTTPS the header contents will only be decrypted by the server, so transportation is safe and adding an HTTP header will suffice. It is adviceable though to keep the credentials in a vault at your server side, so that they never end up in some of the public code repositories.

**Comment by ddeboer** [comment]
@wmelder That’s helpful, thanks!

For us, the question remains how to model the fact that a term source needs authentication (excluding, of course, the credentials themselves, which wil be securely provided by our infrastructure) and passing data to Comunica so it can add [HTTP basic auth](https://comunica.dev/docs/query/advanced/basic_auth/).

**Comment by ddeboer** [comment]
@wmelder Some additional questions to clarify the use case for authenticated endpoints.

You state:

>  The reason is that management wants to know whether services are used or not and by whom.

Makes sense. However, is authentication the appropriate way to solve this? For example, have you considered deriving metrics from the endpoint itself, the web server it runs on or the load balancer in front of it? A very low-key solution is to get metrics by parsing the access logs that you probably already have.

To differentiate between unique clients (rather than having only the grand total number of requests), you could use the client’s IP address.

Moreover, a Network of Terms client key will tell you nothing about the _end_ users of your endpoint, i.e. collection management systems as well as the [demonstrator](https://termennetwerk.netwerkdigitaalerfgoed.nl).

An upside to a metrics-based approach is that we keep the web of data open, without burdening endpoint clients with authentication.

**Comment by wmelder** [comment]
I fully agree with you and adviced to just release an open endpoint, but that was not followed. So we are stuck with this Basic authentication stuff. Besides management metrics, it is also seen as some kind of access control mechanism (by maintenance engineers), to prevent unauthorised users to bring the endpoint down, etc. So, in the end it is fear of the unknown... Hard to reason with that, especially when people are not really supportive for open data to begin with.

**Comment by ddeboer** [comment]
Good to know we’re on the same page, @wmelder. 

I discussed this internally with NDE and our position is that authentication for open data sources should be discouraged. Nevertheless, if it’s really needed we can support authentication in the Network of Terms as long as a single API key for the Network client suffices. This way, we don’t have to bother end users with API keys. 

Will this indeed be the case or does the GTAA endpoint need to differentiate between individual users of the Network of Terms?

**Comment by wmelder** [comment]
> Will this indeed be the case or does the GTAA endpoint need to differentiate between individual users of the Network of Terms?

If I understand this correctly, end users of the netwerk of terms (both UI and API) are depending on the NoT API as middleware. The middleware sends requests to several endpoints, like the GTAA service layer, merges the results and sends these back to the end users. As such, I can not see how end users will have to provide credentials. They just don't know that the N-o-T needs these for the GTAA SPARQL endpoint. 

As the policy is right now, when end users want to query the endpoint themselves, they will need a service account, just like the Network of terms. 


NB There is one thing I would like to test . When we could 'instruct' our reverse proxy to [fake the basic auth](https://httpd.apache.org/docs/2.4/mod/mod_auth_basic.html#authbasicfake) for my test setup, we can do that for the NoT as well. Then you don't have to change the code. That is why I was desperately trying to build the network of terms last week. I was able to build and run the container locally, but when I tried to add changes to the catalog it didn't work and I was instructed to fork both repo's. Then I ended up in more trouble with npm. Hopefully, given the github permissions I was assigned, I can get it to work this week. It might save you some work ;-)

**Comment by ddeboer** [comment]
@wmelder That’s an interesting workaround! 

Let me know if you need help with setting up the repositories. If you want, we can arrange a call this week to work things out.

**Comment by wmelder** [comment]
@ddeboer Let's set up a call. I am running into npm issues again. Linking the packages isn't as easy as the readme says. I could use some help.

**Comment by ddeboer** [comment]
Turned out there was some confusion about how to start a local dev server: @wmelder was using Docker (which may not reflect the local changes to the catalog) whereas an `npm run dev` is the proper course of action. However, that course was not yet documented clearly, which we’ll fix in #487.
