### ISSUE TITLE
Query for specific ConceptScheme when SPARQL endpoints contains more than one.

### ISSUE THREAD

**Issue by wmelder** [netwerk-digitaal-erfgoed/network-of-terms#488]
Some thesauri, like the GTAA, are partitioned using the skos ConceptScheme as categories. When the data for multiple ConceptSchemes is all in the same SPARQL endpoint, it is necessary to specify separate queries for every single ConceptScheme. The main difference in the queries is the object of the skos:inScheme property of the skos:Concepts, being the ConceptScheme itself. It would be beneficial if the skos:ConceptScheme somehow could be seen as a variable for a query, just like the search term is.

**Comment by ddeboer** [comment]
We could generalise this by providing the dataset IRI as a SPARQL query parameter. As long as that matches the `skos:inScheme` (which indeed is the case in #515), you have what you need.
