### ISSUE TITLE
Add K3

### ISSUE THREAD

**Issue by ddeboer** [netwerk-digitaal-erfgoed/network-of-terms#501]
Kerken, Kloosters and Kapellen (K3).

A SPARQL endpoint should be delivered this week.

**Comment by sdevalk** [comment]
A SPARQL endpoint has been made available: https://data.brabantcloud.nl/gebouwen/query

Example query: https://data.brabantcloud.nl/gebouwen/query/?query=select%20*%20where%20{?s%20?p%20?o}%20limit%2010

CIDOC-CRM is used as data model. The model is not finished yet, though -- hopefully soon!

**Comment by sdevalk** [comment]
Closing - terminology source was added in https://github.com/netwerk-digitaal-erfgoed/network-of-terms/pull/621
