### ISSUE TITLE
GTAA queries fail

### ISSUE THREAD

**Issue by EnnoMeijers** [netwerk-digitaal-erfgoed/network-of-terms#534]
With the new release I noticed that the GTAA onderwerpen returns an error, see the graphql output below. My impression is that this is the case for all GTAA sources.
{
  "data": {
    "terms": [
      {
        "source": {
          "uri": "https://data.beeldengeluid.nl/id/datadownload/0031",
          "name": "GTAA: onderwerpen",
          "creators": [
            {
              "uri": "https://www.beeldengeluid.nl/",
              "name": "Nederlands Instituut voor Beeld en Geluid",
              "alternateName": "Beeld en Geluid"
            }
          ]
        },
        "result": {
          "__typename": "ServerError",
          "message": "Invalid SPARQL endpoint response from https://gtaa.apis.beeldengeluid.nl/sparql (HTTP status 403):\nNo key available for any of the roles provided for this user"
        }
      }
    ]
  }
}

**Comment by ddeboer** [comment]
Yep, this is a result of the fact that egress traffic from our Kubernetes cluster to the GTAA endpoint doesn’t have the same IP as the load balancer (which has been whitelisted by Willem). DigitalOcean doesn’t support NAT Gateways, so there’s no way  to guarantee fixed egress IPs. For now, I asked Willem to whitelist the two IPs of our two Kubernetes nodes, which should be relatively stable. 

In the longer term, I’m reinvestigating HTTP authentication support (#478) so we can decouple from whitelisted IPs, and support both development environments and other instances of the Network of Terms, too.

**Comment by wmelder** [comment]
> whitelist the two IPs of our two Kubernetes nodes
Unfortunately, it doesn't seem to help. Still 403. I can try to fake basic auth using the hostname...

**Comment by EnnoMeijers** [comment]
your Kubernetes nodes or ours?

**Comment by ddeboer** [comment]
The NDE Kubernetes nodes, running at DigitalOcean, that the Network of Terms is served at and queries from.

**Comment by wmelder** [comment]
> I can try to fake basic auth using the hostname...

also doesn't work...

**Comment by ddeboer** [comment]
Fixed by allowing our two IP addresses on the side of the GTAA endpoint. I’ll continue generic discussion about authentication in #478.
