### ISSUE TITLE
improve query for gtaa persoonsnamen

### ISSUE THREAD

**Issue by wmelder** [netwerk-digitaal-erfgoed/network-of-terms#558]
I would llike to create an upstream branch for an improved query for GTAA persoonsnamen. Unfortunately, I haven't got the permission to do so. Perhaps an owner can create a branch that I can use to commit a small change?

**Comment by ddeboer** [comment]
Hey @wmelder, fixes to the queries are very welcome! Previously you were given write permissions to this repository, but that’s not really the proper way.

A better way is for you to fork this repository and push changes to your own branch, then create a pull request that we can review and merge into the main repository. See https://docs.github.com/en/get-started/quickstart/contributing-to-projects for an explanation of this process. Let me know if you have any questions!
