### ISSUE TITLE
Improve reconcilation documentation

### ISSUE THREAD

**Issue by EnnoMeijers** [netwerk-digitaal-erfgoed/network-of-terms#598]
The current documentation on the reconcilation api only lists the endpoint for two sources explicitly (RKDArtists, CHT). The statement "and so on for the other sources" is not very helpful if you're not familiar with the N-o-T. I suggest to link to a list sources query on the GraphQL api to give more relevant information to the reader. Maybe add a template syntax like https://termennetwerk-api.netwerkdigitaalerfgoed.nl/reconcile/{source_uri}.

**Comment by ddeboer** [comment]
Documenting a reference to the sources is a good first step (see also #480). 

Additionally, because reconciliation users may not be familiar with GraphQL, we’re considering adding a dynamic list of reconciliation sources to the demonstrator website, for example in the FAQ.

**Comment by EnnoMeijers** [comment]
Sounds like a good plan! 
I was just think of this query on the GraphQL api: `query Sources { sources { uri } }`
Even without knowledge of GraphQL or json this would still informative. So maybe we could add this for now until #480 will be picked up?
