### ISSUE TITLE
reconcilation preview shows the wrong source

### ISSUE THREAD

**Issue by EnnoMeijers** [netwerk-digitaal-erfgoed/network-of-terms#604]
When reconciling against the NTA the preview shows the "Brinkman Trefwoordenthesaurus" as the terminology source.

**Comment by ddeboer** [comment]
The reconciliation preview uses the lookup service, so this is similar to #492: terminology sources that share a URI prefix (and a SPARQL) endpoint will be mixed up in the lookup. 

Both Brinkman and NTA have prefix `http://data.bibliotheken.nl/id/thes/` and SPARQL endpoint `http://data.bibliotheken.nl/sparql`. When a user looks up URI `http://data.bibliotheken.nl/id/thes/foo-bar` we cannot tell from which source the term `foo-bar` comes. 

One way to solve this is to allow queries to return their source (for example using `skos:inScheme`). Other suggestions as to how to fix this are very welcome!

**Comment by EnnoMeijers** [comment]
I think adding support for the KB lookup queries would be useful. We could use this to return the correct source uri and name and fallback to the source definition if inScheme is not set.
