### ISSUE TITLE
Improve Muziekschatten-personen query

### ISSUE THREAD

**Issue by EnnoMeijers** [netwerk-digitaal-erfgoed/network-of-terms#642]
In the muziekschatten-personen.rq search query ?schema_hasOccupation is being defined but never used. Either add this (and others?) to skos:scopeNote field or remove the definition from the query.

**Comment by ddeboer** [comment]
If I’m not mistaken, [is being used](https://github.com/netwerk-digitaal-erfgoed/network-of-terms/blob/master/packages/network-of-terms-catalog/catalog/queries/search/muziekschatten-personen.rq#L51).

**Comment by EnnoMeijers** [comment]
Sorry, your completely right, I overlooked its reuse for scopeNote!
