### ISSUE TITLE
STCN drukkers fails after KB update

### ISSUE THREAD

**Issue by EnnoMeijers** [netwerk-digitaal-erfgoed/network-of-terms#643]
KB has updated the STCN dataset resulting in no results for searches in the N-o-T (try 'Groot', see http://data.bibliotheken.nl/doc/thes/p075547244). 

The sctn.rq for search and lookup needs to be fixed in the following way:

**current:**
?uri foaf:isPrimaryTopicOf/void:inDataset <http://data.bibliotheken.nl/id/dataset/stcn> ;

**new:**
?uri schema:mainEntityOfPage/schema:isPartOf <http://data.bibliotheken.nl/id/dataset/stcn/printers> ;

Note: With the new data there might be additional information to match to or present (contact René Voorburg in more details are needed)...

**Comment by EnnoMeijers** [comment]
Check if this update also fixes issue #500

**Comment by ddeboer** [comment]
Thanks for reporting! Fixed in #644. Unfortunately, #500 is not yet fixed by KB.
