### ISSUE TITLE
Improve RKDArtists results

### ISSUE THREAD

**Issue by EnnoMeijers** [netwerk-digitaal-erfgoed/network-of-terms#720]
When searching in RKDArtists it is quite difficult to disambiguate between the different results, see the results of searching for 'Vincent van Gogh'. It is hard to identify the famous painter from this list. It would help to add the information from the schema:additionalType to skos:scopeNote. In this case this would at least help to identify the painter(s) in the result list.

**Comment by ddeboer** [comment]
Do we actually have this information at the SPARQL endpoint? A [query for Van Gogh](https://data.netwerkdigitaalerfgoed.nl/rkd/rkdartists/sparql/rkdartists#query=PREFIX%20rdf%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%3E%0APREFIX%20rdfs%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E%0ASELECT%20*%20WHERE%20%7B%0A%20%20%3Chttps%3A%2F%2Fdata.rkd.nl%2Fartists%2F32439%3E%20%3Fpred%20%3Fobj.%0A%0A%7D%20LIMIT%20100&endpoint=https%3A%2F%2Fdata.netwerkdigitaalerfgoed.nl%2F_api%2Fdatasets%2Frkd%2Frkdartists%2Fservices%2Frkdartists%2Fsparql&requestMethod=POST&tabTitle=Query&headers=%7B%7D&contentTypeConstruct=application%2Fn-triples%2C*%2F*%3Bq%3D0.9&contentTypeSelect=application%2Fsparql-results%2Bjson%2C*%2F*%3Bq%3D0.9&outputFormat=table) shows no additionalType.

**Comment by EnnoMeijers** [comment]
Ah, good point. I looked at the URI itself using curl -H "Accept: text/turtle" https://data.rkd.nl/artists/32439. This does show the schema:additionalType. RKD is currently working on their LOD publishing infrastructure using their own TriplyDB instance, if I am right it will be available later this year. We should check for this data in the new setup.

**Comment by coret** [comment]
I do see some RKD-KG data in their TriplyDB instance, but at the moment it seems to provide less info about [Vincent](https://api.rkd.triply.cc/s/agQqiCPwy)
