### ISSUE TITLE
GTAA sources not reachable (credential issue)

### ISSUE THREAD

**Issue by coret** [netwerk-digitaal-erfgoed/network-of-terms#790]
When searching GTAA sources, the demonstrator shows

![image](https://user-images.githubusercontent.com/101820/199003492-c1bf3896-9ce0-4601-bf55-33e552690c46.png)

The logfile (network-of-terms-graphql-6444597bd7-5sg7z) shows:

`{"level":"error","time":1667217365094,"name":"http","message":"An error occurred when querying \"https://sys-termennetwerk:****@gtaa.apis.beeldengeluid.nl/sparql\": TypeError: Request cannot be constructed from a URL that includes credentials: https://sys-termennetwerk:N21npG1HZGoY@gtaa.apis.beeldengeluid.nl/sparql"}`

The password changed to **** by me. Manual testing via curl learns that the password is correct and the SPARQL-endpoint is up-and-working. Seems problem in Communica part in Network of Terms?

**Comment by ddeboer** [comment]
Node LTS has moved from 16 to 18, and so have we. On Node 18, passing credentials in URLs seems no longer to be allowed. It’s a bad idea anyway, but we had no other easy options with Comunica and configuration through the catalog. Looking for a solution…

**Comment by wmelder** [comment]
Too bad that new version break stuff. On our proxy, we fake the credentials for the agreed IP address. For now, skipping the credentials would probably re-enable the service. This gives us time to find another solution. Maybe [this page](https://github.com/netwerk-digitaal-erfgoed/network-of-terms/issues/790) can give a hint to fix it?

**Comment by wmelder** [comment]
> {"level":"error","time":1667217365094,"name":"http","message":"An error occurred when querying \"https://********:****@gtaa.apis.beeldengeluid.nl/sparql\": TypeError: Request cannot be constructed from a URL that includes credentials: https://*********:************@gtaa.apis.beeldengeluid.nl/sparql"}

The credentials are exposed in this message, although it is stated that they are replaced with `****`

**Comment by ddeboer** [comment]
Done!
