### ISSUE TITLE
Reconciliation services via termennetwerk-api.netwerkdigitaalerfgoed.nl not producing matches in OpenRefine

### ISSUE THREAD

**Issue by trnstlntk** [netwerk-digitaal-erfgoed/network-of-terms#822]
I am giving an OpenRefine workshop at the Linked Open Limburg Werkconferentie in Limburgs Museum, Venlo in two days (November 24), in which I have been asked to demo the use of the various Termennetwerk reconciliation services, which I'll gladly do.

However, I was just now testing various Termennetwerk services, and none of them seem to produce any matches in OpenRefine. The reconciliation process itself also seems to run only very briefly. I tried with AAT (via Termennetwerk), Thesaurus of Cultural History, RKDartists, and Thesaurus of World Cultures.
The column just ends up entirely unreconciled:
<img width="939" alt="image" src="https://user-images.githubusercontent.com/9881645/203360014-f6efae9d-a660-42f3-aa95-4341d519809f.png">

On the contrary, the 'native' Getty reconciliation endpoint and Wikidata's reconciliation service do provide normal matches, so this is probably not on OpenRefine's side. If the Termennetwerk services don't work this Thursday, I will demo other services and just tell the audience about the existence of the Termennetwerk list of services at https://termennetwerk.netwerkdigitaalerfgoed.nl/faq#openrefine.

**Comment by sdevalk** [comment]
Hi @trnstlntk Thanks! Have you selected the option 'Reconcile against no particular type' in OpenRefine?

<img width="510" alt="Screenshot 2022-11-22 at 17 11 14" src="https://user-images.githubusercontent.com/606948/203364385-02815fa7-279b-49f7-94f0-7e2961633d4e.png">

**Comment by trnstlntk** [comment]
> Hi @trnstlntk Thanks! Have you selected the option 'Reconcile against no particular type' in OpenRefine?

I hadn't! I have just retried several services, and that indeed does the trick. It works now! Thank you.

**Comment by sdevalk** [comment]
Glad that it's working :) I'll close this ticket. Feel free to open new ones in case of other questions or issues.
