### ISSUE TITLE
More descriptive id for GTAA distributions

### ISSUE THREAD

**Issue by EnnoMeijers** [netwerk-digitaal-erfgoed/network-of-terms#886]
The current GTAA sources have a non descriptive distribution ids like https://data.beeldengeluid.nl/id/datadownload/0030. Since the distribution ids are being used in GRAPHQL API calls and the reconcilation API a more descriptive id would be preferable maybe something similar to the dataset id (for this example "http://data.beeldengeluid.nl/gtaa/Persoonsnamen") .  

@wmelder: Could please have a look at this?

**Comment by wmelder** [comment]
@EnnoMeijers Thanks for the question. The distribution ID is needed for specification of the SPARQL endpoint. There is also a distribution defining the OAI-PMH endpoint. The distribution has descriptive metadata, like sdo:name. For example: The Person names via the SPARQL endpoint (distribution/data download): `http://data.beeldengeluid.nl/id/datadownload/0026` 
have a human readable label `sdo:name "GTAA Persoonsnamen"@nl ;` 
We include as little semantic information in the URI as possible. In my opinion it should not be designed for human readability here.
I can imagine it becomes difficult for humans to trace what the source is about, solely looking at the URI. Still, unique and lasting identification is the main role for the identifier. The descriptive metadata should be used to assist human users. This way, it would also be possible to add multiple languages, for example. Maybe show the sdo:name for a resource as a mouse over event?

**Comment by EnnoMeijers** [comment]
@wmelder: Ok, clear! The problem is that currently the distribution id needs to be specified explicitly in the graphql api and the reconcilation api, since this is a human action having a meaningless id could easily lead to mistakes. But apart from using clearer distribution ids I see now easy way out here, using the label (read from the source or specified in the data catalog) will require quite some changes and could lead to other problems like non unique labels, so let's close it for now.
