### ISSUE TITLE
Stimulate alignments of terms

### ISSUE THREAD

**Issue by coret** [netwerk-digitaal-erfgoed/network-of-terms#895]
To stimulate alignments between terms in different sources the owl:sameAs should be returned in the GraphQL API and be shown in the demonstrator. The why/how should be documented in this repo and FAQ.

Note: currently the  rdfs:seeAlso property is part of the interface and shown (as text, not link) in the demonstrator. But this property is not used for alignments.

Examples resource with owl:sameAs in Gouda Timemachine: https://n2t.net/ark:/60537/b3xVzO

**Comment by coret** [comment]
Indeed, lets stick to SKOS and use the vocabulary as defined in [10. Mapping Properties](https://www.w3.org/TR/skos-reference/#mapping).

**Comment by ddeboer** [comment]
Start by mapping `owl:sameAs` in the source data to `skos:exactMatch`.

**Comment by rschalkrce** [comment]
Maybe consider also to map `schema:sameAs` to `skos:exactMatch` (used in NTA, STCN).

**Comment by ddeboer** [comment]
@rschalkrce will produce a list of terminology sources and the predicate that they use (if any) for indicating matches.

**Comment by rschalkrce** [comment]
@ddeboer here is the list of queries and the predicates they use for exact matches:

| query                              | predicate_exactmatch                        |
|------------------------------------|---------------------------------------------|
| aat-materials.rq                  | SKOS:exactMatch                             |
| aat-processes-and-techniques.rq   | SKOS:exactMatch                             |
| aat-styles-and-periods.rq         | SKOS:exactMatch                             |
| aat.rq                             | SKOS:exactMatch                             |
| adamlink-straten.rq               | OWL:sameAs                                  |
| brabantse-gebouwen.rq             | NA                                          |
| brinkman.rq                       | SKOS:exactMatch                             |
| cht-materials.rq                  | SKOS:exactMatch                             |
| cht-styles-and-periods.rq         | SKOS:exactMatch                             |
| eurovoc.rq                        | OWL:sameAs, SKOS:exactmatch                 |
| geonames.rq                       | NA                                          |
| goudatijdmachine-straten.rq       | OWL:sameAs                                  |
| gtaa.rq                           | SKOS:exactMatch                             |
| iconclass.rq                      | NA                                          |
| monumenten.rq                     | NA                                          |
| muziekschatten-onderwerpen.rq     | OWL:sameAs, SKOS:exactmatch                 |
| muziekschatten-personen.rq        | OWL:sameAs, SKOS:exactmatch                 |
| mw-genresstijlen.rq               | OWL:sameAS                                  |
| mw-personengroepen.rq             | OWL:sameAS                                  |
| nmvw.rq                           | SKOS:exactMatch                             |
| nta.rq                            | OWL:sameAs, SKOS:exactmatch, schema:sameAs |
| poolparty.rq                      | SKOS:exactMatch                             |
| rkdartists.rq                     | NA                                          |
| stcn-drukkers.rq                  | OWL:sameAs, SKOS:exactmatch, schema:sameAs |
| uitvoeringsmedium.rq              | OWL:sameAs, SKOS:exactmatch                 |
| wikidata-entities-all.rq          | OWL:sameAs                                  |
| wikidata-entities-persons.rq      | OWL:sameAs                                  |
| wikidata-entities-places.rq       | OWL:sameAs                                  |
| wikidata-entities-streets.rq      | OWL:sameAs                                  |
| wo2thesaurus.rq                   | SKOS:exactMatch                             |
