### ISSUE TITLE
Collect statistics for reporting

### ISSUE THREAD

**Issue by EnnoMeijers** [netwerk-digitaal-erfgoed/network-of-terms#932]
In order to demonstrate the use of the Termennetwerk API we should collect statistics about usage like: number of queries in total and in context of a source, average response times, number of empty result queries, etc. This kind of report is required for formal reporting to the board and the ministry. An aggregated (monthly?) report will be sufficient.

**Comment by rschalkrce** [comment]
@ddeboer is it possible to do this? Some thesauri suppliers are also interested in usage statistics.

**Comment by ddeboer** [comment]
@rschalkrce Yes, we can count queries per source.

**Comment by ddeboer** [comment]
Statistics are now available at https://statistieken.netwerkdigitaalerfgoed.nl (login required).
