### ISSUE TITLE
Recon Service: missing preview data from GeoNames?

### ISSUE THREAD

**Issue by sdevalk** [netwerk-digitaal-erfgoed/network-of-terms#942]
I use NoT's Reconciliation Service in OpenRefine. I try to reconcile my literal place names with GeoNames. However, if I hover over NoT's matches in my reconciliation results, in order to get to see more information about each result, no information is present. Instead, a 'Not found' message appears.

See this screenshot: 
<img width="562" alt="preview" src="https://user-images.githubusercontent.com/606948/231941029-b58b6a0c-d833-40df-b4a9-08f79eeac8e2.png">

Is it possible to show the preview data in the popup?

**Comment by ddeboer** [comment]
Hmm, this seems to be browser-dependent somehow:

* using Chrome, OpenRefine requests https://termennetwerk-api.netwerkdigitaalerfgoed.nl/preview/https://sws.geonames.org/2747929/; this works
* using Safari, https://termennetwerk-api.netwerkdigitaalerfgoed.nl/preview/https://sws.geonames.org/2747929 (missing final `/`) is requested instead; this doesn’t work because GeoNames URIs include a final slash.

Which browser are you using?

**Comment by ddeboer** [comment]
@sdevalk Please try again and see if the fix in #944 resolves your problem.

**Comment by sdevalk** [comment]
Hi @ddeboer Thanks! The preview indeed works on Chrome. It (still) doesn't work on Safari (v 16.1) and Firefox (v 112.0) though.

**Comment by sdevalk** [comment]
@ddeboer A similar issue occurs when I use the new [Data Extension feature](https://github.com/netwerk-digitaal-erfgoed/network-of-terms/issues/935) of the NoT's Reconciliation Service. In OpenRefine I first reconcile a column with RKDartists. I then click on 'Edit column' > 'Add columns from reconciled values'. In the popup I add a new property, 'altLabels'. Then the following message appears: 'Sorry, something went wrong'. See this screenshot:

<img width="1001" alt="Screenshot 2023-04-17 at 06 15 35" src="https://user-images.githubusercontent.com/606948/232376985-44d94286-8ba3-426e-93d2-6bcac7bcfdc8.png">

This happens in Firefox or Safari (not Chrome).

**Comment by ddeboer** [comment]
Please try removing and re-adding the Recon service in OpenRefine. Does that help?

If not, what does your browser error console say?

**Comment by sdevalk** [comment]
@ddeboer That's it! It's now working perfectly :)
