### ISSUE TITLE
No lighthouses via Geonames

### ISSUE THREAD

**Issue by coret** [netwerk-digitaal-erfgoed/network-of-terms#967]
Question Sies:
Why don't I get lighthouses via the Geonames source via the Network of Terms? They are part of the Geonames datasource!

Answer: the Geonames query makes a selection on feature class, lighthouses (feature class S) is not included.

Todo: better describe the Geonames source, for messaging including the selection.

Maybe: consider expanding the number of feature classes.

https://github.com/netwerk-digitaal-erfgoed/network-of-terms/blob/6013848c77fc4aaafa8241f7919497c6e0686912/packages/network-of-terms-catalog/catalog/queries/search/geonames.rq#L26

**Comment by ddeboer** [comment]
This is already documented:

https://github.com/netwerk-digitaal-erfgoed/network-of-terms/blob/6013848c77fc4aaafa8241f7919497c6e0686912/packages/network-of-terms-catalog/catalog/datasets/geonames.jsonld#L19-L24

You’ll find this description when using the GraphQL API.

**Comment by coret** [comment]
This is configuration, not documentation.
